export enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  UNEXPECTED_SERVER_ERROR = 'UNEXPECTED_SERVER_ERROR',
  BAD_USER_REQUEST = 'BAD_USER_REQUEST',
}
